apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-deploy
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: {{ .Release.Name }}-deploy
  type: LoadBalancer